version: "3.9"

tasks:
  up:
    cmds:
      - docker compose --file docker-compose.dev.yml --project-name six-cities up -d
  down:
    cmds:
      - COMPOSE_PROJECT_NAME=six-cities docker-compose --file docker-compose.dev.yml down
